# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#hero"
  weight = 10

[[main]]
  name = "NLP"
  url = "#projects1"
  weight = 20

[[main]]
  name = "TM"
  url = "#projects2"
  weight = 30

[[main]]
  name = "SA"
  url = "#projects3"
  weight = 40

[[main]]
  name = "Docs"
  url = "courses/"
  weight = 50

[[main]]
  name = "Bio"
  url = "#home"
  weight = 60

[[main]]
  name = "Rabbit Hole"
  url = "#contact"
  weight = 70



# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
