---
title: "Country Music Topic Sources"
date: 2020-03-13T14:19:53-05:00
draft: false
links:
  - icon_pack: fab
    name: Docs
    url: courses/example1
  - icon_pack: fab
    name: Slides
    url: slides/example
  - icon_pack: fab
    name: Project
    url: project1/internal-project
bibliography: /home/redapemusic35/VimWiki/Exported-Items.bib
---



<div id="the-thought-experiment" class="section level3">
<h3>The Thought Experiment</h3>
<p>One of the books that I have been working my way through, is a collection of papers on the phenomenon of empathy <span class="citation">(Coplan 2011)</span>. The collection of papers all seek to articulate the phenomenon of empathy as a means of “mind reading,” meaning that empathy helps us to understand or to predict what another might do. Empathy “has been seen as important in relation to our capacity to gain a grasp of the content of other people’s minds, and to predict and explain what they will think, feel, and do” <span class="citation">(Coplan 2011, ix)</span>. Further, empathy has been seen as important for our ethical relations with one another: “in relation to our capacity to respond to others ethically—enabling us not only to gain a grasp of the other’s suffering, but also to respond in an ethically appropriate way” [ix].</p>
<p>I have attempted to argue elsewhere in this project, that <span class="citation">Stump (2010)</span> has a similar treatment of mind reading according to which she argues that narratives provide a way to have what she calls “second personal knowledge” which is a kind of <em>knowledge by acquaintance</em>. If Coplan is right, then using this understanding of second personal knowledge, knowledge of a person by acquaintance, as it might be facilitated by narrative, it might be thought that narrative is a vehicle through which we can come to know others second personally, we come to know what they feel and predict what they may do as a result because of a narratives capacity to induce empathy. Narratives provide a way in which we might come to know others empathically.</p>
<p>There are two ways in which I might be acquainted with another; the first is that I might know certain facts about that person. That they like strawberry flavored ice cream, ride a bike to class 3 days a week, and have never been outside of the country. However, there is another way in which I can come to know a person, and this is through acquaintance, second personally. Further, it seems as though this kind of knowledge can only be had through acquaintance, and that narratives can provide a vehicle by which this acquaintance happens. As such, narratives help us to know others second personally by acquainting us with that person.</p>
<p>Why is all of this important? Well, in <span class="citation">Coplan (2011)</span>’s book, Noël <span class="citation">Carroll (2010)</span> writes about the emotive responses of audiences to fictional characters in narratives. He outlines a number of ways in which the emotions of the audiences either converge, are congruent with, or resonate with those of the characters <span class="citation">(Carroll 2010, 162)</span>.</p>
<p>Here are some relationships between characters and their audiences which he examines:</p>
<ol style="list-style-type: decimal">
<li>Coincidentally occurring emotions; emotions coincidentally occurring simultaneously. This includes:
<ol style="list-style-type: decimal">
<li>the antipathy element of solidarity, simultaneously expressing anger or outrage towards some event or circumstance.</li>
<li>Vectrially converging emotions—these can encompass certain episodes of sympathetic feeling; expressing sympathy towards or for another.</li>
</ol></li>
<li>Mirror reflexes—affective states—these are not fully articulated emotions, but can contribute to their formation. They include merely expressing the same emotions as another, say what might occur in one’s facial expressions which communicates that they understand the pain another shares in a conversation.</li>
</ol>
<p>Central to my emotional data project on a whole, is the idea that it is possible that some types of music may disseminate moral knowledge while others may undermine moral knowledge. To understand whether we might have reason to accept this assertion, I first consider the way music lyrics as narratives, acquaint us with the characters, or the perceived characters that those lyrics are about. Second, we might wonder whether these lyrics facilitate good relationships, in the current case we might say “induce empathy,” assuming that moral knowledge has something to say about what our relationships with others should be like. So to understand how important relationships among people may be in country music, I will run some topic analyses on billboard’s country top 50 for May 23, 2020.</p>
<div id="country-music-files" class="section level5">
<h5>Country Music Files</h5>
<pre class="r"><code>library(magrittr)
library(ggplot2)
library(gridExtra)
library(tidytext)
library(wordcloud2)
library(dplyr)</code></pre>
<pre><code>## 
## Attaching package: &#39;dplyr&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:gridExtra&#39;:
## 
##     combine</code></pre>
<pre><code>## The following objects are masked from &#39;package:stats&#39;:
## 
##     filter, lag</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     intersect, setdiff, setequal, union</code></pre>
<pre class="r"><code>library(readr)
library(tidyr)</code></pre>
<pre><code>## 
## Attaching package: &#39;tidyr&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:magrittr&#39;:
## 
##     extract</code></pre>
<pre class="r"><code>library(stringr)
library(janeaustenr)
library(scales)</code></pre>
<pre><code>## 
## Attaching package: &#39;scales&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:readr&#39;:
## 
##     col_factor</code></pre>
<pre><code>##                   country.songs.chart.from.2020.05.23
##  -----------------------------------: 1              
##  1. &#39;The Bones&#39; by Maren Morris     : 1              
##  10. &#39;Bluebird&#39; by Miranda Lambert  : 1              
##  11. &#39;Here And Now&#39; by Kenny Chesney: 1              
##  12. &#39;One Margarita&#39; by Luke Bryan  : 1              
##  13. &#39;In Between&#39; by Scotty McCreery: 1              
##  (Other)                            :45</code></pre>
<pre><code>##                                     r.b.hip.hop.songs.chart.from.2020.05.30
##  ---------------------------------------                : 1                
##  1. &#39;Savage&#39; by Megan Thee Stallion Featuring Beyonce   : 1                
##  10. &#39;The Scotts&#39; by THE SCOTTS, Travis Scott &amp; Kid Cudi: 1                
##  11. &#39;Blueberry Faygo&#39; by Lil Mosey                     : 1                
##  12. &#39;High Fashion&#39; by Roddy Ricch Featuring Mustard    : 1                
##  13. &#39;Whats Poppin&#39; by Jack Harlow                      : 1                
##  (Other)                                                :45</code></pre>
<pre><code>##                                        shelton-stefani-nobody-but-you.txt 
##                                   &quot;&quot; &quot;shelton-stefani-nobody-but-you.txt&quot; 
##                 lambert-bluebird.txt            mccollum-pretty-heart.txt 
##               &quot;lambert-bluebird.txt&quot;          &quot;mccollum-pretty-heart.txt&quot; 
##          stell-everywhere-but-on.txt          dominion-some-people-do.txt 
##        &quot;stell-everywhere-but-on.txt&quot;        &quot;dominion-some-people-do.txt&quot;</code></pre>
<pre><code>##          godzilla.txt            savage.txt   blueberry-faygo.txt 
##        &quot;godzilla.txt&quot;          &quot;savage.txt&quot; &quot;blueberry-faygo.txt&quot; 
##      walk-em-down.txt          go-crazy.txt        solitaires.txt 
##    &quot;walk-em-down.txt&quot;        &quot;go-crazy.txt&quot;      &quot;solitaires.txt&quot;</code></pre>
</div>
</div>
<div id="topic-analysis-on-countrys-top-songs" class="section level2">
<h2>Topic Analysis on Country’s Top Songs</h2>
<p>One particularly interesting aspect of this discussion is Carroll’s idea that sympathy for a character governs whether the audience will empathize with that character <span class="citation">(Carroll 2010, 174)</span>. In other words, in order for an audience to empathize with a character, they most first be able to sympathize with that character. Further, what determines whether the audience will sympathize with a character, is whether the audience is capable of having altruistic attitudes towards the characters in question. In order to experience emotions of altruism, the audience perceives them as morally good. However, sometimes what causes us to determine whether someone is morally good, is that their interests align with ours, or whether that person’s interests align with those of her community in a way in which our own would in a similar situation. Carroll calls these kinds of factors factors of kinship, group membership, group interests etc. We like people who get along well, and care about those in their community who are good, and we resonate and therefore sympathize with them.</p>
<p>After cleaning the data considerably, I have two frames of data each of which consists of two columns. The first frame has 1,160 lines of data while the second has 2,733. Each line in the first frame is a tokenized version of all of the lyrics in either the country, first frame, or hip-hop, second frame. A token is merely a word from a lyric while the right column consists of the number of instances of that token in the entire corpus whether hip-hop or country.</p>
<pre><code>## # A tibble: 1,254 x 2
##    word      n
##    &lt;chr&gt; &lt;int&gt;
##  1 ai      127
##  2 love    109
##  3 yeah     88
##  4 girl     57
##  5 wanna    54
##  6 night    51
##  7 heart    49
##  8 hope     46
##  9 time     46
## 10 baby     40
## # … with 1,244 more rows</code></pre>
<pre><code>## # A tibble: 2,804 x 2
##    word       n
##    &lt;chr&gt;  &lt;int&gt;
##  1 yeah     526
##  2 bitch    161
##  3 nigga    137
##  4 niggas   130
##  5 ai       127
##  6 shit     121
##  7 ayy      116
##  8 love      68
##  9 gon       66
## 10 time      63
## # … with 2,794 more rows</code></pre>
<p>What I show here, are two distinct data frames. The first includes those words which are used most frequently in the top 50 country songs of the billboard country charts, taken May 23, 2020. Ignoring “ai” (which I believe is a malformed version of the word “ain’t) which shows to have been repeated 127 times in 50 sets of lyrics, the most frequent word used in these lyrics is”love&quot; at 107 usage instance in 50 song lyrics. The next, “yeah” should likely be articulated as a <em>stop-word</em> as should “ai.” Stop-words are words like “and,” “the,” “it,” and are typically not thought of as contributing to the content meaning in a data source.</p>
<p><img src="/post1/Country-top-100_files/figure-html/unnamed-chunk-6-1.png" width="672" /><img src="/post1/Country-top-100_files/figure-html/unnamed-chunk-6-2.png" width="672" /></p>
<p>What I find highly meaningful here, are the stark differences in those words used in each set of data. For instance, while words like “love,” “hope,” “heart,” make for the most used words in the country set, more derogatory and disparaging language is used in the hip-hop set.</p>
</div>
<div id="more-comparisons" class="section level2">
<h2>More Comparisons</h2>
<p>Another way in which we might compare two sets of song lyrics in order to determine their moral content, is by comparing the those words which they use in common. What I mean by this, is that a way to compare the language in two sets of data, is by comparing the frequency of which they use the same words.</p>
<p>To do so, I will compare the language used in Jane Austen’s “Sense and Sensibility,” the Bronte Sister’s “Jane Eyre,” “Wuthering Heights,” “The Tenant of Wildfell Hall,” and “Agnes Grey,” and H.G. Well’s “The Time Machine,” “The War of the Worlds,” “The Invisible Man,” and “The Island of Doctor Moreau.”</p>
<p>Obviously the data sets built from the novels above are quite a bit larger than those of the country and hip-hop data sets. However, the algorithm I use, as I will show, does a very good job, nevertheless in distinguishing between each of these. Yet, for other reasons, what follows next may not be the best comparison made, i.e., we might naturally expect differences in language in this way given that each of these are written in different historical periods. Yet, as I will show, it is still the case that the language used in the country set is more similar to that used in each of the novels.</p>
<pre><code>## # A tibble: 73,422 x 4
##    text                    book                linenumber chapter
##    &lt;chr&gt;                   &lt;fct&gt;                    &lt;int&gt;   &lt;int&gt;
##  1 &quot;SENSE AND SENSIBILITY&quot; Sense &amp; Sensibility          1       0
##  2 &quot;&quot;                      Sense &amp; Sensibility          2       0
##  3 &quot;by Jane Austen&quot;        Sense &amp; Sensibility          3       0
##  4 &quot;&quot;                      Sense &amp; Sensibility          4       0
##  5 &quot;(1811)&quot;                Sense &amp; Sensibility          5       0
##  6 &quot;&quot;                      Sense &amp; Sensibility          6       0
##  7 &quot;&quot;                      Sense &amp; Sensibility          7       0
##  8 &quot;&quot;                      Sense &amp; Sensibility          8       0
##  9 &quot;&quot;                      Sense &amp; Sensibility          9       0
## 10 &quot;CHAPTER 1&quot;             Sense &amp; Sensibility         10       1
## # … with 73,412 more rows</code></pre>
<pre><code>## Joining, by = &quot;word&quot;</code></pre>
<pre><code>## # A tibble: 13,914 x 2
##    word       n
##    &lt;chr&gt;  &lt;int&gt;
##  1 miss    1855
##  2 time    1337
##  3 fanny    862
##  4 dear     822
##  5 lady     817
##  6 sir      806
##  7 day      797
##  8 emma     787
##  9 sister   727
## 10 house    699
## # … with 13,904 more rows</code></pre>
<p><img src="/post1/Country-top-100_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<pre><code>## Determining mirror for Project Gutenberg from http://www.gutenberg.org/robot/harvest</code></pre>
<pre><code>## Using mirror http://aleph.gutenberg.org</code></pre>
<pre><code>## Joining, by = &quot;word&quot;</code></pre>
<pre><code>## # A tibble: 11,769 x 2
##    word       n
##    &lt;chr&gt;  &lt;int&gt;
##  1 time     454
##  2 people   302
##  3 door     260
##  4 heard    249
##  5 black    232
##  6 stood    229
##  7 white    222
##  8 hand     218
##  9 kemp     213
## 10 eyes     210
## # … with 11,759 more rows</code></pre>
<pre><code>## Joining, by = &quot;word&quot;</code></pre>
<pre><code>## # A tibble: 23,050 x 2
##    word       n
##    &lt;chr&gt;  &lt;int&gt;
##  1 time    1065
##  2 miss     855
##  3 day      827
##  4 hand     768
##  5 eyes     713
##  6 night    647
##  7 heart    638
##  8 looked   601
##  9 door     592
## 10 half     586
## # … with 23,040 more rows</code></pre>
<pre><code>## # A tibble: 57,818 x 4
##    word        `Jane Austen` author          proportion
##    &lt;chr&gt;               &lt;dbl&gt; &lt;chr&gt;                &lt;dbl&gt;
##  1 a              0.00000919 Bronte Sisters  0.0000319 
##  2 a&#39;most        NA          Bronte Sisters  0.0000159 
##  3 a&#39;n&#39;t          0.00000460 Bronte Sisters NA         
##  4 aback         NA          Bronte Sisters  0.00000398
##  5 abaht         NA          Bronte Sisters  0.00000398
##  6 abandon       NA          Bronte Sisters  0.0000319 
##  7 abandoned      0.00000460 Bronte Sisters  0.0000916 
##  8 abandoning    NA          Bronte Sisters  0.00000398
##  9 abandonment   NA          Bronte Sisters  0.0000199 
## 10 abart         NA          Bronte Sisters NA         
## # … with 57,808 more rows</code></pre>
<p>In the first frame, I have broken up Jane Austen’s “Sense and Sensibility” into lines. Each line constitutes an actual line as printed in the Project Gutenberg version of the book. Next, in the second frame, I have created a token from each word in the book and counted the number of times that this token is used. For instance, you will see that the word “miss,” is the most frequently used word at 1855 instances.</p>
<p>In the fourth frame, I count the number of instances of a particular word in the H.G. Well’s novels. You will see here that the word “time” occurs the most frequently at 454 instances. Finally, in the fifth frame, the words “time,” and “miss” are the most frequently occurring in the Bronte Sister’s novels.</p>
<p>In the frame immediately following this one, I compare the Jane Austen novels against the Bronte Sister’s and H.G. Wells’ novels. Those words closest to the dotted line running though the middle of the frame are those words with the most similarly usage frequency. I.e., the words “miss” and “time” have a similar usage frequency in the Jane Austen and Bronte Sister’s novels. It is likely that this is to be expected given that the lives of Jane Austen and the Bronte Sisters overlapped—though they wrote in different styles—while H.G. Wells wrote in the late 19th and early 20th century <span class="citation">(Robinson n.d.)</span>. Additionally, those words further from the dotted line in the middle, are words that found more in one text than in the other. Consequently, looking at the Bronte Sisters, words like “Elizabeth” are found more in Jane Austen novels than they are in novels written by the Bronte Sisters. Looking at H.G. Wells, words like “miss” are found more in Jane Austen novels than in H.G. Wells while words like “smoke” are found more in H.G. Wells than in Jane Austen.</p>
<pre><code>## Warning: Removed 41357 rows containing missing values (geom_point).</code></pre>
<pre><code>## Warning: Removed 41359 rows containing missing values (geom_text).</code></pre>
<p><img src="/post1/Country-top-100_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<pre><code>## Joining, by = &quot;word&quot;</code></pre>
<pre><code>## # A tibble: 13,914 x 2
##    word       n
##    &lt;chr&gt;  &lt;int&gt;
##  1 miss    1855
##  2 time    1337
##  3 fanny    862
##  4 dear     822
##  5 lady     817
##  6 sir      806
##  7 day      797
##  8 emma     787
##  9 sister   727
## 10 house    699
## # … with 13,904 more rows</code></pre>
<p><img src="/post1/Country-top-100_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<pre><code>## # A tibble: 16,119 x 2
##     line word        
##    &lt;int&gt; &lt;chr&gt;       
##  1     2 shelton     
##  2     2 stefani     
##  3     2 nobody      
##  4     2 but         
##  5     2 you.txt     
##  6     3 lambert     
##  7     3 bluebird.txt
##  8     4 mccollum    
##  9     4 pretty      
## 10     4 heart.txt   
## # … with 16,109 more rows</code></pre>
<pre><code>## # A tibble: 29,575 x 2
##     line word          
##    &lt;int&gt; &lt;chr&gt;         
##  1     1 godzilla.txt  
##  2     2 savage.txt    
##  3     3 blueberry     
##  4     3 faygo.txt     
##  5     4 walk          
##  6     4 em            
##  7     4 down.txt      
##  8     5 go            
##  9     5 crazy.txt     
## 10     6 solitaires.txt
## # … with 29,565 more rows</code></pre>
<pre><code>## Joining, by = &quot;word&quot;
## Joining, by = &quot;word&quot;
## Joining, by = &quot;word&quot;</code></pre>
<pre><code>## # A tibble: 13,914 x 2
##    word       n
##    &lt;chr&gt;  &lt;int&gt;
##  1 miss    1855
##  2 time    1337
##  3 fanny    862
##  4 dear     822
##  5 lady     817
##  6 sir      806
##  7 day      797
##  8 emma     787
##  9 sister   727
## 10 house    699
## # … with 13,904 more rows</code></pre>
<pre><code>## # A tibble: 2,804 x 2
##    word       n
##    &lt;chr&gt;  &lt;int&gt;
##  1 yeah     526
##  2 bitch    161
##  3 nigga    137
##  4 niggas   130
##  5 ai       127
##  6 shit     121
##  7 ayy      116
##  8 love      68
##  9 gon       66
## 10 time      63
## # … with 2,794 more rows</code></pre>
<pre><code>## Warning: Removed 15417 rows containing missing values (geom_point).</code></pre>
<pre><code>## Warning: Removed 15419 rows containing missing values (geom_text).</code></pre>
<p><img src="/post1/Country-top-100_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
<pre><code>## Warning: Removed 15417 rows containing missing values (geom_point).</code></pre>
<pre><code>## Warning: Removed 15419 rows containing missing values (geom_text).</code></pre>
<p><img src="/post1/Country-top-100_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<p>If Stump is right, or if I am right in representing her argument, one way in which we can know someone, is by having the same, or similar feelings as the person in response to the same object. However, for this to happen, I question whether the language must be a shared language.</p>
<p>For instance, in the frame following this one, I make more comparisons in the ways in which language is used between country, hip-hop, the Bronte Sisters, Jane Austen and H.G. Wells.</p>
<pre><code>## Warning: Removed 42227 rows containing missing values (geom_point).</code></pre>
<pre><code>## Warning: Removed 42229 rows containing missing values (geom_text).</code></pre>
<p><img src="/post1/Country-top-100_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<p>One thing to notice about the above frame, and this is similar through this post, is that those data sets which have more similar word usage are typically noted by a denser plot while those with less similar word usages are noted by more transparent plots. As such, looking at the previous frame, we see that the Bronte Sisters have a more similar word usage to Country music than does Hip-Hop.</p>
</div>
<div id="conclusion" class="section level1">
<h1>Conclusion</h1>
<p>In one of my earlier posts, I stated that it seems that country music uses more relationship words than hip-hop, and that positive emotional sentiments are often expressed in the presence of relationships whereas negative emotional sentiments are expressed when those relationships become threatened. Conversely, it seems that the opposite is true in many contemporary and popular hip-hop songs. Positive emotional sentiments are expressed in context of objects rather than people whereas negative emotional sentiments are expressed in terms of human relationships. Although I have not shown the emotive correlations between these sets of data, in other posts, for instance under the menu heading “Sentiment Analysis,” I have. However, it would be important to do so on these texts to see what kind of relationships, if any, there are between those words used, and the emotive expressions which accompany them.</p>
<p>Therefore, if we are to say that morality is about relationships between people, then one way to possibly measure moral knowledge in a narrative, would be to determine whether the narrative is about relationships, and whether it expresses what we might think ought to be expressed in the same or similar context.</p>
</div>
<div id="works-cited" class="section level1 unnumbered">
<h1>Works Cited</h1>
<div id="refs" class="references">
<div id="ref-carr10">
<p>Carroll, Noël. 2010. <em>On Some Affective Relations Between Audiences and the Characters in Popular Fictions</em>. <em>Empathy</em>. Oxford University Press. <a href="https://www.oxfordscholarship.com/view/10.1093/acprof:oso/9780199539956.001.0001/acprof-9780199539956-chapter-12" class="uri">https://www.oxfordscholarship.com/view/10.1093/acprof:oso/9780199539956.001.0001/acprof-9780199539956-chapter-12</a>.</p>
</div>
<div id="ref-copl11b">
<p>Coplan, Amy, ed. 2011. <em>Empathy: Philosophical and Psychological Perspectives</em>. <em>Empathy</em>. Oxford University Press. <a href="https://www.oxfordscholarship.com/view/10.1093/acprof:oso/9780199539956.001.0001/acprof-9780199539956" class="uri">https://www.oxfordscholarship.com/view/10.1093/acprof:oso/9780199539956.001.0001/acprof-9780199539956</a>.</p>
</div>
<div id="ref-robi00">
<p>Robinson, Julia Silge and David. n.d. <em>1 the Tidy Text Format | Text Mining with R</em>. Accessed June 4, 2020. <a href="https://www.tidytextmining.com/" class="uri">https://www.tidytextmining.com/</a>.</p>
</div>
<div id="ref-stum10">
<p>Stump, Eleonore. 2010. <em>Wandering in Darkness: Narrative and the Problem of Suffering</em>. Oxford, New York: Oxford University Press.</p>
</div>
</div>
</div>
