---
title: "Country Topic Models"
date: 2020-03-13T14:19:53-05:00
draft: false
diagram: true
links:
  - icon_pack: fab
    name: Methods
    url: courses/example2
bibliography: /home/redapemusic35/VimWiki/Exported-Items.bib
---

Here, we have a range of topics denoted in factors from 0 to 40.

```r chunk_blame, echo = TRUE}
setwd("/home/redapemusic35/mallet")
words <- read.csv("Country_keys.csv", header = TRUE, sep = ",")
head(words)
tail(words)
```

I graph them below. Along the y access is shown the percentage of probability that the set of words corresponding with one of the topics 0 through 40. Along the x axis is show the topic number.

```{r chunk_name, echo = FALSE} 
require(graphics)
library(ggrepel)
library(gridExtra)
data(mtcars)
library(ggplot2)
setwd("~/mallet/")
keys3 <- read.csv("Rap_keys1.csv", header = TRUE, sep = ",")
Edges3 <- read.csv("Edges.csv", header = TRUE, sep = ",")
all3 <- merge(keys3, Edges3, by = "Topics")

with(all3, scatter.smooth(Topics, Order, lpars =
  list(col = "red", lwd = 3, lty = 3)))

```

Next I will combine the two graphs by inserting the individual terms making up a particular topic.

```r combined words and topics, echo = FALSE}
library(ggrepel)
library(gridExtra)
data(mtcars)
library(ggplot2)
setwd("~/mallet/")
keys <- read.csv("Rap_keys1.csv", header = TRUE, sep = ",")
Edges <- read.csv("Edges.csv", header = TRUE, sep = ",")
all <- merge(keys, Edges, by = "Topics")

ggplot(all, aes(Topics, Order)) +
  geom_point(color = "red") +
  geom_text_repel(data = subset(all, Order > 0.04),
 segment.size = 0.15,
segment.alpha = 1.0,
aes(
color = factor(Topics),
label = Words,
))
```

Seems to get 68% of its words from topic number 27, 20% from topic number 18, 5% from topic 17 and 8% from topic 39. Anything less than 5% I chose not to show.

Below I do the same with the top 14 country songs from the billboard top 100. Some interesting features to note include possibly the kinds of terms making up the topic. But also, what is interesting is the distribution of the topics. There is a much tighter clustering than in the Hip Hip set. However I am not sure what the significance of the distribution is. One possibility I think might be the substance of the topic and the fact that there does seem to be a much higher chance the what the document is about, can be seen in the cluster of terms comprising the dominant topic.

First, the keys themselves:

```r Country Keys, echo = FALSE}

setwd("~/mallet/")
keys11 <- read.csv("Edge.csv", header = TRUE, sep = ",")

head(keys11$Type)
tail(keys11$Type)
```

```r country words, echo = FALSE}
library(ggrepel)
library(gridExtra)
data(mtcars)
library(ggplot2)
setwd("~/mallet/")
keys1 <- read.csv("Country_keys.csv", header = TRUE, sep = ",")
Edges1 <- read.csv("Country_word_topics.csv", header = TRUE, sep = ",")
all1 <- merge(x = keys1, y = Edges1, by = "Topic")

ggplot(all1, aes(Topic, Order)) +
  geom_point(color = "red") +
  geom_text_repel(data = subset(all1, Order > 0.02),
 segment.size = 0.15,
segment.alpha = 1.0,
aes(
color = factor(Topic),
label = Words,
))
```

I should point out that in HH, I suppressed any and all terms which constituted less than 5% percentage of the topic distribution. As such, in HH only shows 4 topics overall while Country shows considerably more. Additionally, you will notice that on the right side of the graph just above is a graph which is titled "factor(Topic)." These are those topics which are denoted by the terms on the graph. For HH, all topics with greater than 5% percentage and for Country greater than 2%.

The thing that I find most interesting here, is that in the first graph there are no relationship words, love, friend, lonely, cheats, you, her, etcetera. However, in the second set, there are many relationship words.

In the next section, SA in the menu, I will show some preliminary sentiment analysis on these texts.

```r Morris echo = FALSE}

setwd("/home/redapemusic35/")

Morris <- read.csv("/VimWiki/subjects/digital-humanities/stanford-output-dir/Country/Morris/Morris/bones.txt", header = FALSE, sep = ",")
head(Morris)

```

# Notes
