---
# Display name
title: In the Pursuit of Moral Knowledge
name: Abstract

# Username (this should match the folder name)
# authors:
# - admin

# Is this the primary user of the site?
# superuser: true

# Role/position
# role: Phd Student, Philosophy

# Organizations/Affiliations
# organizations:
# - name: Saint Louis University
#   url: ""

# Short bio (displayed in user profile at end of posts)
bio: Hi and welcome to my project. 

# interests:
# - Virtue Epistemology
# - Philosophy of Religion
# - Moral Psychology

# education:
#   courses:
#   - course: PhD in Philosophy
#     institution: Saint Louis University
#    year: 2023
#   - course: MA in Philosophy
#     institution: Oklahoma State University
#     year: 2017
#   - course: BA in Philosophy
#     institution: Seattle Pacific University
#     year: 2015

# Social/Academic Networking
# For available icons, see: https://sourcethemes.com/academic/docs/page-builder/#icons
#   For an email link, use "fas" icon pack, "envelope" icon, and a link in the
#   form "mailto:your-email@example.com" or "#contact" for contact widget.
# social:
# - icon: envelope
#   icon_pack: fas
#   link: '#contact'  # For a direct email link, use "mailto:test@example.org".
# - icon: twitter
#   icon_pack: fab
#   link: https://twitter.com/GeorgeCushen
# - icon: google-scholar
#   icon_pack: ai
#   link: https://scholar.google.co.uk/citations?user=sIwtMXoAAAAJ
# - icon: github
#   icon_pack: fab
#   link: https://github.com/redapemusic35
# Link to a PDF of your resume/CV from the About widget.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# - icon: cv
#   icon_pack: ai
#   link: files/cv.pdf

# Enter email to display Gravatar (if Gravatar enabled in Config)
# email: ""

# Organizational groups that you belong to (for People widget)
#   Set this to `[]` or comment out if you are not using People widget.
# user_groups:
# - Researchers
# - Visitors
bibliography: /home/redapemusic35/VimWiki/Exported-Items.bib
---

In her book “Wandering in
Darkness,” Eleonore @stum10 argues that
narrative can be a source of knowledge. The elevator speech of this view, is that narrative is a kind of moral testimony which communicates moral knowledge. This is because unlike standard moral testimony, narratives communicate not only emotions the character feels in a given situation, but also provides a framework as to what emotions the audience may experience in a similar situation. On this presupposition, I will attempt to use natural language processing and data mining to explore methods in which we might find sources of moral knowledge and sources which may undermine moral knowledge.

There are many ways in which one can organize a website. As such, there are many ways in which a website can be navigated. Given that I intend to offer a kind of argument, in favor of the above thesis, the way I have thought best to organize this website, is in terms of premises. As such, I suggest that the best way to navigate this particular site is to think of it as an argument where the links in the menu section above, constitute the primary premises. 

Accordingly, I suggest that after reading this portion, that my reader continue by clicking on "Introduction" and reading the post "Introduction to NLP, Data Mining and Moral Knowledge." Here, I explain my motivation for creating this project. I argue why I think that we are justified in thinking of narrative as a source for moral knowledge. First, we rely on others for knowledge. In the same way, we rely on others for moral knowledge. There are two ways in which others become sources for moral knowledge. The first is that we learn by observing others and the second is through the testimony of others. Narratives I argue facilitate both ways of learning.

Next, I suggest clicking on the menu item labeled "Data Sources." There, you will be taken to a page with two additional links. These explain the methodology I used in choosing and creating the data sets that I use in the analysis. I attempted to keep my data sources as narrow as possible. As such, on March 13, I visited BillBoard's top100 Music Charts. I randomly selected genres based on what I thought might represent the two most distinctive narrative contents. These are the Country Music and Hip Hop music genres. Accordingly, the first link show my country sources while the second my Hip Hop music sources.

Next, selecting the menu item labeled "Topic Modeling" explains what topic modeling is and how I use it. I conclude this section by arguing that topic modeling by itself does not tell anything about moral knowledge. Topic modeling, by itself, does not tell us whether a particular narrative contributes to, or takes away from, moral knowledge. This is because while useful in informing us what a piece of literature is about, it does not tell us how we ought to feel regarding what the literature is about. 

As such, in the next section labeled "Sentiment Analysis," I suggest that maybe sentiment analysis can further help us to determine whether a narrative contributes to or takes away from our moral knowledge. I argue then, that sentiment analysis can give us a way of determining whether a piece of literature contributes to or undermines our moral knowledge.

Clicking on those links in the menu at the top of each page then, will take you to a page with three additional links. Each of these links best represent supporting premises in order of appearance. 

# Works Cited
